<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PluginsPath>F:\Game\PlantsVsZombies\dev\Culib\plugins</PluginsPath>
	<InnerPath>F:\Game\PlantsVsZombies\dev\Culib\in_plugins</InnerPath>
    <ModsPath>F:\Game\PlantsVsZombies\dev\Culib\mod</ModsPath>
	<BepResPath>F:\Game\PlantsVsZombies\dev\Culib\res</BepResPath>
	<MelonResPath>F:\Game\PlantsVsZombies\dev\Culib\mres</MelonResPath>
  </PropertyGroup>
  <ItemGroup>
    <!-- 绉婚櫎鎵€鏈塂LL寮曠敤锛堜繚鐣橮rojectReference锛?-->
    <Reference Remove="@(Reference)" />
    
    <!-- 娣诲姞鍏ㄥ眬BepInEx寮曠敤 -->
    <Reference Include="F:\Game\PlantsVsZombies\dev\Culib\lib\*.dll" 
               Exclude="F:\Game\PlantsVsZombies\dev\Culib\lib\dobby.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(BepResPath)&quot;" />
  <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(PluginsPath)&quot;" />
</Target>
	<PropertyGroup>
		<NoWarn>$(NoWarn);MSB3277</NoWarn>
	</PropertyGroup>
</Project>


























































